server:
  port: 3001

spring:
  application:
    name: edumate-backend
  
  # MySQL Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/edumate_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: edumate_user
    password: edumate_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb://localhost:27017/edumate_mongo
      auto-index-creation: true
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

# JWT Configuration
jwt:
  secret: edumate-secret-key-for-jwt-token-generation-and-validation
  expiration: 86400000 # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins: http://localhost:5173,http://localhost:5174
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# AI Configuration
ai:
  gemini:
    api-keys:
      - AIzaSyAtRJvydFU-UZUDnK3Eq3Zx5WE_XKax8Z4
      - AIzaSyAQT5usx8_0dOvg68fFjFxrIjPCXBQ9Gmw
      - AIzaSyDu-C7YYqZ8oZsyXOi5S8qEAG5kECm_qJk
    base-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
    max-tokens: 2048

# File Storage Configuration
file:
  upload-dir: ./uploads
  max-size: 10485760 # 10MB

# Logging
logging:
  level:
    com.edumate: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
